# Generated by Django 3.1.7 on 2021-03-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='payment_token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
