# Generated by Django 3.1.7 on 2021-03-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(choices=[('a', 'Average'), ('b', 'Bad'), ('e', 'Excellent')], default='a', max_length=1),
            preserve_default=False,
        ),
    ]
