# Generated by Django 3.1.7 on 2021-03-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0002_auto_20210315_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='hey', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(choices=[('e', 'Excellent'), ('a', 'Average'), ('b', 'Bad')], max_length=1),
        ),
    ]
