# Generated by Django 3.1.7 on 2021-03-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0003_auto_20210316_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(choices=[('a', 'Average'), ('e', 'Excellent'), ('b', 'Bad')], max_length=1),
        ),
    ]
