# Generated by Django 3.1.7 on 2021-03-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0004_auto_20210316_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(choices=[('e', 'Excellent'), ('a', 'Average'), ('b', 'Bad')], max_length=1),
        ),
    ]
