# Generated by Django 3.1.7 on 2021-03-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0005_auto_20210317_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(choices=[('a', 'Average'), ('e', 'Excellent'), ('b', 'Bad')], max_length=1),
        ),
    ]
