# Generated by Django 3.1.7 on 2021-03-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0006_auto_20210317_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(choices=[('a', 'Average'), ('b', 'Bad'), ('e', 'Excellent')], max_length=1),
        ),
    ]
