# Generated by Django 3.1.7 on 2021-03-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_width', models.CharField(max_length=100)),
                ('image_height', models.CharField(max_length=100)),
            ],
        ),
    ]
